version: '2'
 
services:
  mysql:
    image: mysql
    container_name: mysql-spring
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=test
    #restart: always
    networks:
      - spring_mysql_network
 
  musine:
    depends_on:
      - mysql
    image: davidefregonese/musine
    container_name: musine
    ports:
      - 8443:8443
    links:
      - mysql:mysql
    networks:
      - spring_mysql_network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/test

networks:
  spring_mysql_network:
    driver: bridge