version: "2.0"

services: 
  musinehost:
    image: daniribeiro/musine-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=musine
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
  webapp:
    image: daniribeiro/musine
    depends_on:
      - musinehost
    ports:
      - 8443:8443
    environment:
      - DATABASE_HOST=daniribeirohost
      - DATABASE_USER=root
      - DATABASE_PASSWORD=
      - DATABASE_NAME=daniribeiro
      - DATABASE_PORT=3306
  daniribeiroAngular:
    image: daniribeiro/musine-angular
    depends_on:
      - webapp
    ports:
      - 4200:80
    environment:
      - API_URL=webapp